"""add archived fields to giveaways

Revision ID: 04786b369e8c
Revises: 49a3c9f9b68b
Create Date: 2026-08-16 03:29:35.445395

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '04786b369e8c'
down_revision: Union[str, None] = '49a3c9f9b68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        # server_default обязателен: без него SQLite отказывается добавлять NOT
        # NULL колонку в уже непустую таблицу (тот же паттерн, что и
        # amount_mismatch — см. миграцию 712b493850ae, DECISIONS.md).
        batch_op.add_column(
            sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
