"""add messages_allowed to channel_bindings

Revision ID: 0d83124fd1e4
Revises: 3cc3f35458a0
Create Date: 2026-07-21 09:24:54.661443

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d83124fd1e4'
down_revision: Union[str, None] = '3cc3f35458a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_bindings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages_allowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_bindings', schema=None) as batch_op:
        batch_op.drop_column('messages_allowed')

    # ### end Alembic commands ###
