"""initial schema

Revision ID: 2c1dbba9e7ed
Revises: 
Create Date: 2026-07-13 07:05:24.579931

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c1dbba9e7ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('PANEL_USER', 'PARTICIPANT', 'SYSTEM', 'BANK', name='auditactortype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('audience_filter', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', name='broadcaststatus', native_enum=False), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('max_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_issued', sa.Integer(), nullable=False),
    sa.Column('tickets_reserved', sa.Integer(), nullable=False),
    sa.Column('is_registration_open', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('digital_poster_path', sa.String(length=500), nullable=True),
    sa.Column('digital_poster_caption', sa.String(length=2000), nullable=True),
    sa.Column('poster_media_cache', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giveaways_prefix'), ['prefix'], unique=True)

    op.create_table('panel_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMINISTRATOR', 'OPERATOR', name='paneluserrole', native_enum=False), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panel_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_users_login'), ['login'], unique=True)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_phone'), ['phone'], unique=True)

    op.create_table('channel_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'VK', 'MAX', name='channeltype', native_enum=False), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_user_id', name='uq_channel_external_user'),
    sa.UniqueConstraint('participant_id', 'channel', name='uq_participant_channel')
    )
    with op.batch_alter_table('channel_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_bindings_external_user_id'), ['external_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_bindings_participant_id'), ['participant_id'], unique=False)

    op.create_table('manual_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='manualregistrationstatus', native_enum=False), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['panel_users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_registrations_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_registrations_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_registrations_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TBANK', 'VTB', 'MOCK', name='paymentprovidertype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('raw_webhook_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('poll_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_provider_override', sa.Enum('TBANK', 'VTB', 'MOCK', name='paymentprovidertype', native_enum=False), nullable=True),
    sa.Column('ignore_phone_verification', sa.Boolean(), nullable=False),
    sa.Column('online_status_poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('online_status_poll_max_attempts', sa.Integer(), nullable=False),
    sa.Column('online_reservation_ttl_sec', sa.Integer(), nullable=False),
    sa.Column('manual_reservation_ttl_sec', sa.Integer(), nullable=False),
    sa.Column('support_contacts', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['panel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('shuffle_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('FREE', 'RESERVED', 'ISSUED', name='ticketpoolstatus', native_enum=False), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('manual_registration_id', sa.Integer(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['manual_registration_id'], ['manual_registrations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giveaway_id', 'number', name='uq_giveaway_number')
    )
    with op.batch_alter_table('ticket_pool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_pool_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_pool_shuffle_order'), ['shuffle_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_pool_status'), ['status'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giveaway_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('full_code', sa.String(length=50), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ONLINE', 'MANUAL', name='ticketsource', native_enum=False), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('manual_registration_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['manual_registration_id'], ['manual_registrations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['ticket_pool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('giveaway_id', 'number', name='uq_ticket_giveaway_number'),
    sa.UniqueConstraint('pool_id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_full_code'), ['full_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_giveaway_id'), ['giveaway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_participant_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_giveaway_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_full_code'))

    op.drop_table('tickets')
    with op.batch_alter_table('ticket_pool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_pool_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_pool_shuffle_order'))
        batch_op.drop_index(batch_op.f('ix_ticket_pool_giveaway_id'))

    op.drop_table('ticket_pool')
    op.drop_table('platform_settings')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_participant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_giveaway_id'))

    op.drop_table('payments')
    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_manual_registrations_participant_id'))
        batch_op.drop_index(batch_op.f('ix_manual_registrations_giveaway_id'))

    op.drop_table('manual_registrations')
    with op.batch_alter_table('channel_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_bindings_participant_id'))
        batch_op.drop_index(batch_op.f('ix_channel_bindings_external_user_id'))

    op.drop_table('channel_bindings')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_phone'))

    op.drop_table('participants')
    with op.batch_alter_table('panel_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_users_login'))

    op.drop_table('panel_users')
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giveaways_prefix'))

    op.drop_table('giveaways')
    op.drop_table('broadcasts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
