"""add cashless qr payment fields to manual registrations

Revision ID: 2e75fb17a907
Revises: 318cef609231
Create Date: 2026-07-27 19:28:07.492769

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e75fb17a907'
down_revision: Union[str, None] = '318cef609231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        # server_default обязателен: без него SQLite отказывается добавлять NOT
        # NULL колонку в уже непустую таблицу (см. efd96eba5b08 — тот же боевой
        # инцидент). Существующие строки трактуются как CASH, что соответствует
        # их фактическому смыслу до появления этой фичи.
        batch_op.add_column(
            sa.Column(
                'payment_method',
                sa.Enum('CASH', 'CASHLESS', name='manualregistrationpaymentmethod', native_enum=False),
                nullable=False,
                server_default='CASH',
            )
        )
        batch_op.add_column(sa.Column('payment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qr_code_payload', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('qr_generated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_manual_registrations_giveaway_id_payment_number', ['giveaway_id', 'payment_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_manual_registrations_giveaway_id_payment_number', type_='unique')
        batch_op.drop_column('qr_generated_at')
        batch_op.drop_column('qr_code_payload')
        batch_op.drop_column('payment_number')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
