"""add payment_url and qr_code_payload to payments

Revision ID: 4cbeb5a0084a
Revises: 80c572c9e87e
Create Date: 2026-07-14 16:40:54.588405

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4cbeb5a0084a'
down_revision: Union[str, None] = '80c572c9e87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('qr_code_payload', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('qr_code_payload')
        batch_op.drop_column('payment_url')

    # ### end Alembic commands ###
