"""widen broadcasts status column for cancelled

Revision ID: 5467f57e04b5
Revises: ed1b690eea2a
Create Date: 2026-09-22 19:09:22.297926

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5467f57e04b5'
down_revision: Union[str, None] = 'ed1b690eea2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', 'CANCELLED', name='broadcaststatus', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', 'CANCELLED', name='broadcaststatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
