"""add payment amount_mismatch fields

Revision ID: 712b493850ae
Revises: efd96eba5b08
Create Date: 2026-07-25 02:35:18.923167

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '712b493850ae'
down_revision: Union[str, None] = 'efd96eba5b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # server_default обязателен: без него SQLite отказывается добавлять NOT
        # NULL колонку в уже непустую таблицу (тот же боевой инцидент, что и с
        # oversold/payment_number — см. миграцию efd96eba5b08, DECISIONS.md).
        batch_op.add_column(
            sa.Column('amount_mismatch', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('amount_mismatch_bank_amount', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('amount_mismatch_bank_amount')
        batch_op.drop_column('amount_mismatch')

    # ### end Alembic commands ###
