"""index operator_id and created_at for pagination filters

Revision ID: 80c572c9e87e
Revises: 2c1dbba9e7ed
Create Date: 2026-07-14 15:41:55.858263

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80c572c9e87e'
down_revision: Union[str, None] = '2c1dbba9e7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_registrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_registrations_operator_id'), ['operator_id'], unique=False)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_created_at'))

    with op.batch_alter_table('manual_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_registrations_operator_id'))
        batch_op.drop_index(batch_op.f('ix_manual_registrations_created_at'))

    # ### end Alembic commands ###
