"""widen pending_channel_deliveries status for undeliverable

Revision ID: 8828f80abfd6
Revises: 5467f57e04b5
Create Date: 2026-09-22 19:57:26.013825

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8828f80abfd6'
down_revision: Union[str, None] = '5467f57e04b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_channel_deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('PENDING', 'SENT', 'UNDELIVERABLE', name='pendingdeliverystatus', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_channel_deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'SENT', 'UNDELIVERABLE', name='pendingdeliverystatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
