"""add bank_reconciliation_runs

Revision ID: ae6c278bb969
Revises: 0ea4e7087990
Create Date: 2026-07-26 03:20:13.749186

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae6c278bb969'
down_revision: Union[str, None] = '0ea4e7087990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FETCH_FAILED', name='bankreconciliationrunstatus', native_enum=False), nullable=False),
    sa.Column('candidates_checked', sa.Integer(), nullable=False),
    sa.Column('entries_fetched', sa.Integer(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('ttl_expired_count', sa.Integer(), nullable=False),
    sa.Column('finalize_error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_reconciliation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_reconciliation_runs_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_reconciliation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_reconciliation_runs_started_at'))

    op.drop_table('bank_reconciliation_runs')
    # ### end Alembic commands ###
