"""add pending_channel_deliveries

Revision ID: ed1b690eea2a
Revises: 49a3c9f9b68b
Create Date: 2026-09-22 13:54:15.056653

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed1b690eea2a'
down_revision: Union[str, None] = '49a3c9f9b68b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_channel_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'VK', 'MAX', name='channeltype', native_enum=False), nullable=False),
    sa.Column('external_user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.Enum('TEXT_MESSAGE', 'QR_CODE', 'DELIVER_PURCHASE', name='pendingdeliverykind', native_enum=False), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', name='pendingdeliverystatus', native_enum=False), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_channel_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_channel_deliveries_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_channel_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_channel_deliveries_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_channel_deliveries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_channel_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_channel_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_pending_channel_deliveries_participant_id'))
        batch_op.drop_index(batch_op.f('ix_pending_channel_deliveries_created_at'))
        batch_op.drop_index(batch_op.f('ix_pending_channel_deliveries_channel'))

    op.drop_table('pending_channel_deliveries')
    # ### end Alembic commands ###
