"""add payment number, oversold and payment receipts

Revision ID: efd96eba5b08
Revises: 57406f29fb2b
Create Date: 2026-07-22 23:16:21.256184

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efd96eba5b08'
down_revision: Union[str, None] = '57406f29fb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('vk_attachment', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_receipts_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipts_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_payment_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('oversold', sa.Boolean(), nullable=False))
        batch_op.alter_column('provider',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('TBANK', 'VTB', 'MOCK', 'REQUISITES_QR', name='paymentprovidertype', native_enum=False),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_payments_giveaway_id_payment_number', ['giveaway_id', 'payment_number'])

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('payment_provider_override',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('TBANK', 'VTB', 'MOCK', 'REQUISITES_QR', name='paymentprovidertype', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.alter_column('payment_provider_override',
               existing_type=sa.Enum('TBANK', 'VTB', 'MOCK', 'REQUISITES_QR', name='paymentprovidertype', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payments_giveaway_id_payment_number', type_='unique')
        batch_op.alter_column('provider',
               existing_type=sa.Enum('TBANK', 'VTB', 'MOCK', 'REQUISITES_QR', name='paymentprovidertype', native_enum=False),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
        batch_op.drop_column('oversold')
        batch_op.drop_column('payment_number')

    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_column('next_payment_number')

    with op.batch_alter_table('payment_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_receipts_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_payment_receipts_payment_id'))

    op.drop_table('payment_receipts')
    # ### end Alembic commands ###
